steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$SHORT_SHA", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$SHORT_SHA"]
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./deployment.yaml
  - --image=gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$_IMAGE_VERSION
  - --location=us-central1-c
  - --cluster=standard-cluster-1
